#!/bin/bash
# Cart Testing Automation Script
# This script helps automate the testing checklist

echo "🧪 Baby Cotton Club - Cart Testing Script"
echo "=========================================="
echo ""

# Check if server is running
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null ; then
    echo "✅ Development server is running on http://localhost:3000"
else
    echo "❌ Development server is NOT running"
    echo "Starting server..."
    npm start &
    sleep 10
    echo "✅ Server started"
fi

echo ""
echo "📋 Manual Testing Checklist:"
echo ""
echo "1. Open http://localhost:3000 in your browser"
echo "2. Press F12 to open Developer Tools"
echo "3. Go to Console tab"
echo ""
echo "Expected console message:"
echo "   🔍 Cart Debug Tools Loaded!"
echo ""
echo "Available debug commands:"
echo "   - inspectCart()      → View cart state"
echo "   - testCartUpdate()   → Test API call"
echo "   - fixCartTypes()     → Fix type issues"
echo "   - clearCartDebug()   → Clear cart"
echo ""
echo "📝 Testing Sequence:"
echo ""
echo "Step 1: Login"
echo "   □ Click 'Login' in navigation"
echo "   □ Enter credentials"
echo "   □ Verify login successful"
echo ""
echo "Step 2: Test Product WITHOUT Size"
echo "   □ Find product without sizes (e.g., bedding)"
echo "   □ Click 'Add to Cart'"
echo "   □ Check console for success message"
echo "   □ Verify cart icon updates"
echo ""
echo "Step 3: Test Product WITH Size"
echo "   □ Find product with sizes (e.g., clothing)"
echo "   □ Try adding WITHOUT selecting size (should fail)"
echo "   □ Select a size (S, M, L, XL)"
echo "   □ Click 'Add to Cart'"
echo "   □ Check console - size should be in payload"
echo "   □ Verify cart icon updates"
echo ""
echo "Step 4: Inspect Cart"
echo "   □ In console, type: inspectCart()"
echo "   □ Verify all green checkmarks ✅"
echo "   □ Check no red errors ❌"
echo ""
echo "Step 5: View Cart Page"
echo "   □ Click cart icon"
echo "   □ Verify all items shown with correct details"
echo "   □ Verify sizes are displayed"
echo ""
echo "Step 6: Update Quantities"
echo "   □ Click + button (increase)"
echo "   □ Check console for update success"
echo "   □ Click - button (decrease)"
echo "   □ Click Remove"
echo ""
echo "Step 7: Test Checkout"
echo "   □ Add multiple items"
echo "   □ Click 'Proceed to Checkout'"
echo "   □ Check console for 3 cart updates"
echo "   □ Verify no 400 errors"
echo ""
echo "Step 8: Verify API Calls"
echo "   □ In console, type: testCartUpdate()"
echo "   □ Check for success response"
echo "   □ If 400 error, run: inspectCart()"
echo ""
echo "🔧 If Issues Found:"
echo ""
echo "Run in console:"
echo "   fixCartTypes()    → Fix type mismatches"
echo "   clearCartDebug()  → Start fresh"
echo "   inspectCart()     → Diagnose issues"
echo ""
echo "Check documentation:"
echo "   - CART_TESTING_GUIDE.md"
echo "   - DEBUGGING_400_ERROR.md"
echo "   - CART_DEBUG_TOOLS.md"
echo ""
echo "✅ Server is ready for testing!"
echo "Open http://localhost:3000 and follow the checklist above"
echo ""
